# name: AdminLTE Clickthrough Screenshot

# on:
#   workflow_dispatch:
#     inputs:
#       section:
#         description: 'Sidebar section name (e.g., Widgets, Charts, Tables)'
#         required: true
#         default: 'Widgets'

# jobs:
#   run-selenium:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'

#       - name: Install dependencies
#         run: pip install -r requirements.txt

#       - name: Install Chrome and Chromedriver
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y wget unzip xvfb libxi6 libgconf-2-4
#           wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#           sudo apt install -y ./google-chrome-stable_current_amd64.deb
#           CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
#           DRIVER_URL=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | jq -r ".channels.Stable.downloads.chromedriver[] | select(.platform == \"linux64\") | .url")
#           wget $DRIVER_URL -O chromedriver.zip
#           unzip chromedriver.zip
#           sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
#           sudo chmod +x /usr/bin/chromedriver

#       - name: Run screenshot script for section ${{ github.event.inputs.section }}
#         run: python take_screenshot.py "${{ github.event.inputs.section }}"

#       - name: Upload screenshot as artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: section-screenshot
#           path: screenshots/