name: AAP Sidebar Screenshot

on:
  workflow_dispatch:
    inputs:
      section:
        description: 'Sidebar section to capture (e.g., Billing, Dashboard, Tables)'
        required: true
        default: 'Billing'

jobs:
  capture-screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Selenium script for ${{ github.event.inputs.section }}
        run: python sidebar_screenshot.py "${{ github.event.inputs.section }}"

      - name: Upload screenshot artifact
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: screenshots/